// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/coder.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class coder {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object Alph=null;
  public static String guardados=null;
  static {
    int $line=0;
    $line=22;
    $try:try {
      guardados=$defaultValue(String.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet Q=null;
  static {
    int $line=0;
    $line=24;
    $try:try {
      Q=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet estadosImpares=null;
  static {
    int $line=0;
    $line=26;
    $try:try {
      estadosImpares=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet estadosTransicionImpares=null;
  static {
    int $line=0;
    $line=27;
    $try:try {
      estadosTransicionImpares=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet estadosPares1=null;
  static {
    int $line=0;
    $line=29;
    $try:try {
      estadosPares1=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet estadosPares2=null;
  static {
    int $line=0;
    $line=30;
    $try:try {
      estadosPares2=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet estadosPares3=null;
  static {
    int $line=0;
    $line=31;
    $try:try {
      estadosPares3=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet estadosPares4=null;
  static {
    int $line=0;
    $line=32;
    $try:try {
      estadosPares4=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet estadosPares=null;
  static {
    int $line=0;
    $line=33;
    $try:try {
      estadosPares=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet estadosTransicionPares=null;
  static {
    int $line=0;
    $line=35;
    $try:try {
      estadosTransicionPares=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet letritas=null;
  static {
    int $line=0;
    $line=37;
    $try:try {
      letritas=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static ISet simbolitos=null;
  static {
    int $line=0;
    $line=38;
    $try:try {
      simbolitos=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,null,$line);
    }
  }
  public static Object chars(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v1=$newSet();
      int $v3=$int(0);
      int $v4=$int($invokeMethod("length",string,new Object[]{}))-1;
      $v2:for (int i=$v3; i<=$v4; i++) {
        $v1.add($invokeMethod("charAt",string,new Object[]{i}));
      }
      $result=$v1;
      if (true) break $try;
      $line=41;
      $rethrow(new RuntimeException("The function \"chars(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"chars",$line);
    }
    return $result;
  }
  public static Object charsStrings(Object strings) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v5=$newSet(GCollections.emptySet());
      $v6:for (Object s:GCollections.unmodifiableCollection(strings)) {
        $v5.union(GCollections.unmodifiableSet(((java.lang.Iterable)(coder.chars(s)))));
      }
      $result=$v5;
      if (true) break $try;
      $line=42;
      $rethrow(new RuntimeException("The function \"charsStrings(strings:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"charsStrings",$line);
    }
    return $result;
  }
  public static Object prefixes(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v7=$newSet();
      int $v9=$int(1);
      int $v10=$int($invokeMethod("length",string,new Object[]{}));
      $v8:for (int i=$v9; i<=$v10; i++) {
        $v7.add($invokeMethod("substring",string,new Object[]{0,i}));
      }
      $result=$v7;
      if (true) break $try;
      $line=44;
      $rethrow(new RuntimeException("The function \"prefixes(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"prefixes",$line);
    }
    return $result;
  }
  public static Object allPrefixes(Object strings) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v11=$newSet(GCollections.emptySet());
      $v12:for (Object s:GCollections.unmodifiableCollection(strings)) {
        $v11.union(GCollections.unmodifiableSet(((java.lang.Iterable)(coder.prefixes(s)))));
      }
      $result=$v11;
      if (true) break $try;
      $line=45;
      $rethrow(new RuntimeException("The function \"allPrefixes(strings:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"allPrefixes",$line);
    }
    return $result;
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=50;
      if ($opEqualY($invokeField("length",args),0)) {
        $line=50;
        Alph=$fix(GCollections.asSet('a','c','t'));
      }
      else {
        $line=52;
        gold.structures.set.ISet $v13=$newSet();
        int $v15=$int(0);
        int $v16=$int($invokeMethod("length",((java.lang.String[])args)[$int(0)],new Object[]{}))-1;
        $v14:for (int i=$v15; i<=$v16; i++) {
          $v13.add($invokeMethod("charAt",((java.lang.String[])args)[$int(0)],new Object[]{i}));
        }
        Alph=$fix($opDiffeY($v13,GCollections.asSet('$','#')));
      }
      $line=55;
      Object T=$fix(coder.createTransducer());
      $line=56;
      System.out.println($message(new Object[]{"Estrada para el coder: "}));
      $line=58;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,T));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"main",$line);
    }
  }
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=65;
      Object Ls=$fix(GCollections.asSet("a","b","c","d"));
      $line=66;
      gold.structures.set.ISet $v17=$newSet();
      $v18:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        $v17.add($opAdditY("",a));
      }
      Object M1=$fix($v17);
      $line=67;
      gold.structures.set.ISet $v19=$newSet();
      $v20:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        for (Object b:GCollections.unmodifiableCollection(Ls)) {
          $v19.add($opAdditY($opAdditY("",a),b));
        }
      }
      Object M2=$fix($v19);
      $line=68;
      gold.structures.set.ISet $v21=$newSet();
      $v22:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        for (Object b:GCollections.unmodifiableCollection(Ls)) {
          for (Object c:GCollections.unmodifiableCollection(Ls)) {
            $v21.add($opAdditY($opAdditY($opAdditY("",a),b),c));
          }
        }
      }
      Object M3=$fix($v21);
      $line=69;
      gold.structures.set.ISet $v23=$newSet();
      $v24:for (Object s:GCollections.unmodifiableCollection($opUnionY($opUnionY(M1,M2),M3))) {
        $v23.add(s);
      }
      Object MF=$fix($v23);
      $line=71;
      letritas=$cast(ISet.class,$fix(GCollections.asSet("a","b","c","d")));
      $line=72;
      simbolitos=$cast(ISet.class,$fix(GCollections.asSet("!","#")));
      $line=74;
      gold.structures.set.ISet $v25=$newSet();
      $v26:for (Object s:GCollections.unmodifiableCollection(MF)) {
        $v25.add(GCollections.asList(s,"1"));
      }
      estadosImpares=$cast(ISet.class,$fix($v25));
      $line=75;
      gold.structures.set.ISet $v27=$newSet();
      $v28:for (Object s:GCollections.unmodifiableCollection(M3)) {
        $v27.add(GCollections.asList(s,"!"));
      }
      estadosTransicionImpares=$cast(ISet.class,$fix($v27));
      $line=77;
      gold.structures.set.ISet $v29=$newSet();
      $v30:for (Object s:GCollections.unmodifiableCollection(M3)) {
        $v29.add(GCollections.asList(s,$invokeMethod("substring",s,new Object[]{0,1})));
      }
      estadosPares1=$cast(ISet.class,$fix($v29));
      $line=78;
      gold.structures.set.ISet $v31=$newSet();
      $v32:for (Object s:GCollections.unmodifiableCollection(M3)) {
        $v31.add(GCollections.asList(s,$invokeMethod("substring",s,new Object[]{0,2})));
      }
      estadosPares2=$cast(ISet.class,$fix($v31));
      $line=79;
      gold.structures.set.ISet $v33=$newSet();
      $v34:for (Object s:GCollections.unmodifiableCollection(M3)) {
        $v33.add(GCollections.asList(s,s));
      }
      estadosPares3=$cast(ISet.class,$fix($v33));
      $line=80;
      gold.structures.set.ISet $v35=$newSet();
      $v36:for (Object s:GCollections.unmodifiableCollection(MF)) {
        $v35.add(GCollections.asList(s,"2"));
      }
      estadosPares4=$cast(ISet.class,$fix($v35));
      $line=81;
      estadosPares=$cast(ISet.class,$fix($opUnionY($opUnionY($opUnionY(estadosPares1,estadosPares2),estadosPares3),estadosPares4)));
      $line=83;
      Q=$cast(ISet.class,$fix($opUnionY($opUnionY($opUnionY(estadosImpares,estadosPares),estadosTransicionImpares),GCollections.asSet("INIT","#","!2"))));
      $line=84;
      Object \u03A3=$fix($opUnionY(coder.charsStrings(letritas),coder.charsStrings(simbolitos)));
      $line=85;
      Object O=$fix($opUnionY(\u03A3,GCollections.asSet('*')));
      $line=86;
      Object q_0=$fix("INIT");
      $line=87;
      Object F=$fix(Q);
      $line=89;
      System.out.println($message(new Object[]{Q}));
      $line=90;
      System.out.println($message(new Object[]{\u03A3}));
      $line=92;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,O,q_0,F,new GMethod(coder.class,"\u03B4"),new GMethod(coder.class,"imprEstados"),new GMethod(coder.class,"imprFlechas")});
      if (true) break $try;
      $line=93;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object imprEstados(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=98;
      if ($opEqualY(q,"#")) {
        $line=99;
        $result="#";
        if (true) break $try;
      }
      else {
        $line=101;
        if ($opEqualY(q,"!2")) {
          $line=102;
          $result="!";
          if (true) break $try;
        }
        else {
          $line=104;
          if ($opMembrY(q,estadosTransicionImpares)) {
            $line=105;
            $result="!";
            if (true) break $try;
          }
          else {
            $line=107;
            if ($opMembrY(q,estadosPares3)) {
              $line=108;
              $result="*";
              if (true) break $try;
            }
            else {
              $line=110;
              if ($opMembrY(q,estadosImpares)) {
                $line=111;
                String palabra=null;
                palabra=$defaultValue(String.class);
                $line=112;
                palabra=$cast(String.class,$fix($getArrayValue(q,new Object[]{0})));
                $line=114;
                if ($opEqualY(((java.lang.String)palabra).length(),3)) {
                  $line=115;
                  $result=palabra;
                  if (true) break $try;
                }
                else {
                  $line=118;
                  $result="";
                  if (true) break $try;
                }
              }
              else {
                $line=121;
                if ($opMembrY(q,estadosPares4)) {
                  $line=122;
                  String palabra=null;
                  palabra=$defaultValue(String.class);
                  $line=123;
                  palabra=$cast(String.class,$fix($getArrayValue(q,new Object[]{0})));
                  $line=125;
                  if ($opEqualY(((java.lang.String)palabra).length(),3)) {
                    $line=126;
                    $result=palabra;
                    if (true) break $try;
                  }
                  else {
                    $line=129;
                    $result="";
                    if (true) break $try;
                  }
                }
                else {
                  $line=133;
                  $result="";
                  if (true) break $try;
                }
              }
            }
          }
        }
      }
      $line=138;
      $rethrow(new RuntimeException("The function \"imprEstados(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"imprEstados",$line);
    }
    return $result;
  }
  public static Object imprFlechas(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=143;
      $result="";
      if (true) break $try;
      $line=144;
      $rethrow(new RuntimeException("The function \"imprFlechas(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"imprFlechas",$line);
    }
    return $result;
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=150;
      if ($opEqualY(q,"INIT")) {
        $line=151;
        if ($opMembrY($opAdditY("",\u03C3),letritas)) {
          $line=152;
          $result=GCollections.asList($opAdditY("",\u03C3),"1");
          if (true) break $try;
        }
        else {
          $line=153;
          $result="#";
          if (true) break $try;
        }
      }
      else {
        $line=156;
        if ($opEqualY(q,"#")) {
          $line=157;
          $result="#";
          if (true) break $try;
        }
        else {
          $line=159;
          if ($opMembrY(q,estadosImpares)) {
            $line=160;
            String letras=null;
            letras=$defaultValue(String.class);
            $line=161;
            letras=$cast(String.class,$fix($getArrayValue(q,new Object[]{0})));
            $line=162;
            if ($opMembrY($opAdditY("",\u03C3),letritas)) {
              $line=163;
              if ($opLessqY(((java.lang.String)letras).length(),2)) {
                $line=164;
                $result=GCollections.asList($opAdditY(letras,\u03C3),"1");
                if (true) break $try;
              }
              else {
                $line=165;
                $result="#";
                if (true) break $try;
              }
            }
            else {
              $line=168;
              if ($opEqualY($opAdditY("",\u03C3),"!")) {
                $line=169;
                if ($opEqualY(((java.lang.String)letras).length(),3)) {
                  $line=170;
                  $result=GCollections.asList(letras,"!");
                  if (true) break $try;
                }
                else {
                  $line=171;
                  $result="#";
                  if (true) break $try;
                }
              }
              else {
                $line=174;
                if ($opEqualY($opAdditY("",\u03C3),"#")) {
                  $line=175;
                  $result="#";
                  if (true) break $try;
                }
                else {
                  $line=177;
                  $result="#";
                  if (true) break $try;
                }
              }
            }
          }
          else {
            $line=180;
            if ($opMembrY(q,estadosPares)) {
              $line=181;
              String letras1=null;
              letras1=$defaultValue(String.class);
              $line=182;
              String letras2=null;
              letras2=$defaultValue(String.class);
              $line=183;
              letras1=$cast(String.class,$fix($getArrayValue(q,new Object[]{0})));
              $line=184;
              letras2=$cast(String.class,$fix($getArrayValue(q,new Object[]{1})));
              $line=186;
              if ($opMembrY(q,estadosPares4)) {
                $line=187;
                if ($opMembrY($opAdditY("",\u03C3),letritas)) {
                  $line=188;
                  if ($opLessqY(((java.lang.String)letras1).length(),2)) {
                    $line=189;
                    $result=GCollections.asList($opAdditY(letras1,\u03C3),"2");
                    if (true) break $try;
                  }
                  else {
                    $line=190;
                    $result="#";
                    if (true) break $try;
                  }
                }
                else {
                  $line=193;
                  if ($opEqualY($opAdditY("",\u03C3),"!")) {
                    $line=194;
                    if ($opEqualY(((java.lang.String)letras1).length(),3)) {
                      $line=195;
                      $result="!2";
                      if (true) break $try;
                    }
                    else {
                      $line=196;
                      $result="#";
                      if (true) break $try;
                    }
                  }
                  else {
                    $line=199;
                    if ($opEqualY($opAdditY("",\u03C3),"#")) {
                      $line=200;
                      $result="#";
                      if (true) break $try;
                    }
                    else {
                      $line=202;
                      $result="#";
                      if (true) break $try;
                    }
                  }
                }
              }
              else {
                $line=205;
                if ($opMembrY(q,$opUnionY($opUnionY(estadosPares1,estadosPares2),estadosPares3))) {
                  $line=207;
                  if ($opMembrY($opAdditY("",\u03C3),letritas)) {
                    $line=208;
                    if ($opLessqY(((java.lang.String)letras2).length(),2)) {
                      $line=209;
                      if ($opMembrY(GCollections.asList(letras1,$opAdditY(letras2,\u03C3)),Q)) {
                        $line=210;
                        $result=GCollections.asList(letras1,$opAdditY(letras2,\u03C3));
                        if (true) break $try;
                      }
                      else {
                        $line=212;
                        $result=GCollections.asList($opAdditY(letras2,\u03C3),"2");
                        if (true) break $try;
                      }
                    }
                    else {
                      $line=215;
                      $result="#";
                      if (true) break $try;
                    }
                  }
                  else {
                    $line=218;
                    if ($opEqualY($opAdditY("",\u03C3),"!")) {
                      $line=219;
                      if (($opEqualY(((java.lang.String)letras2).length(),3)&&$opMembrY(GCollections.asList(letras1,letras2),Q))) {
                        $line=220;
                        $result="!2";
                        if (true) break $try;
                      }
                      else {
                        $line=221;
                        $result="#";
                        if (true) break $try;
                      }
                    }
                    else {
                      $line=224;
                      if ($opEqualY($opAdditY("",\u03C3),"#")) {
                        $line=225;
                        $result="#";
                        if (true) break $try;
                      }
                      else {
                        $line=227;
                        $result="#";
                        if (true) break $try;
                      }
                    }
                  }
                }
                else {
                  $line=230;
                  $result="#";
                  if (true) break $try;
                }
              }
            }
            else {
              $line=234;
              if ($opMembrY(q,estadosTransicionImpares)) {
                $line=235;
                String letras=null;
                letras=$defaultValue(String.class);
                $line=236;
                letras=$cast(String.class,$fix($getArrayValue(q,new Object[]{0})));
                $line=238;
                if ($opMembrY($opAdditY("",\u03C3),letritas)) {
                  $line=239;
                  if ($opMembrY(GCollections.asList(letras,$opAdditY("",\u03C3)),Q)) {
                    $line=240;
                    $result=GCollections.asList(letras,$opAdditY("",\u03C3));
                    if (true) break $try;
                  }
                  else {
                    $line=243;
                    $result=GCollections.asList($opAdditY("",\u03C3),"2");
                    if (true) break $try;
                  }
                }
                else {
                  $line=246;
                  $result="#";
                  if (true) break $try;
                }
              }
              else {
                $line=249;
                if ($opEqualY(q,"!2")) {
                  $line=250;
                  if ($opMembrY($opAdditY("",\u03C3),letritas)) {
                    $line=251;
                    $result=GCollections.asList($opAdditY("",\u03C3),"1");
                    if (true) break $try;
                  }
                  else {
                    $line=252;
                    $result="#";
                    if (true) break $try;
                  }
                }
                else {
                  $line=255;
                  $result="#";
                  if (true) break $try;
                }
              }
            }
          }
        }
      }
      $line=260;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,coder.class,"\u03B4",$line);
    }
    return $result;
  }
}
